In [1]:
import numpy as np

In [38]:
#Task 1
arr=np.array([[1,0,1],[1,1,1],[1,1,1],[1,1,1]])
np.all(arr)

False

In [44]:
#Task 2
arr=np.array([[0,0,0],[0,0,0],[0,0,0],[0,0,0]])
np.any(arr)

False

In [3]:
#Task 3
def equality(x,y):
    print(np.equal(x,y))
m1=np.array([[1.22,2.33,3],[1,2,5],[0,3.79,0.8]])
m2=np.array([[1,2.33,3],[1,2,5],[0,4,1]])
equality(m1,m2)


[[False  True  True]
 [ True  True  True]
 [ True False False]]


In [18]:
# Task 4
zeros=np.array([0]*10)
ones=np.array([1]*10)
fives=np.array([5]*10)
print(zeros)
print(ones)
print(fives)
print(type(zeros))
print(type(ones))
print(type(fives))

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [20]:
#Task 5
np.arange(30,71,1)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [23]:
#Task 6
Identity=np.identity(3)
print(Identity)
print(Identity.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [33]:
#task 7
np.random.rand(10)

array([0.62274399, 0.5208883 , 0.23546348, 0.85879753, 0.85504713,
       0.11908949, 0.95036458, 0.56965931, 0.01236968, 0.77162601])

In [45]:
#Task 8
np.random.randn(15)

array([-0.34923712, -1.41227658, -0.27221059,  0.24389833, -0.23540718,
        0.2088937 , -0.9088115 , -0.61087875, -0.74000006, -0.47266216,
        0.94457059, -0.06083386, -0.58915443,  0.19850696,  1.27547903])

In [2]:
#Task 9
arr=np.arange(15,56,1)
arr[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [7]:
# Task 10
arr=np.linspace(0,10,5)
print(arr)
arr2=np.random.randint(0,11,5)
arr2

[ 0.   2.5  5.   7.5 10. ]


array([0, 4, 5, 1, 6])

In [10]:
# Task 11
arr=np.ones((10,10))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
# Task 12
np.diagflat([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [12]:
# Task 13
arr = np.zeros((4, 4))
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
arr

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [29]:
#Task 14
from tempfile import TemporaryFile
arr1=np.ones((3,3))
arr2=np.zeros((3,3))
file=TemporaryFile()
np.savez(file, arr1, arr2)
file.seek(0) 
npzfile = np.load(file)
npzfile.files
print(npzfile['arr_0'])
print('\n')
print(npzfile['arr_1'])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#Task 15 
np.random.seed(10)
print(np.random.rand(40))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]
